export const types = {
	AUTH_SIGNUP: 'AUTH_SIGNUP',
	AUTH_SIGNIN: 'AUTH_SIGNIN',

	GET_BOOKS: 'GET_BOOKS',
	GET_BOOKS_SEARCH: 'GET_BOOKS_SEARCH',
	BOOK_CLEAR_SEARCH: 'BOOK_CLEAR_SEARCH',
	BOOK_SET_ACTIVE: 'BOOK_SET_ACTIVE',

	GET_AUTHORS: 'GET_AUTHORS',
	GET_AUTHOR_BY_ID: 'GET_AUTHOR_BY_ID',

	LIST_GET_LIST_BY_USER: 'GET_LIST_BY_USER',
	LIST_GET_LIST_BY_ID: 'GET_LIST_BY_ID',
	LIST_ADD_BOOK_TO_LIST: 'LIST_ADD_BOOK_TO_LIST',
	LIST_REMOVE_BOOK_FROM_LIST: 'LIST_REMOVE_BOOK_FROM_LIST',

	UI_SHOW_MODAL: 'UI_SHOW_MODAL',
	UI_HIDE_MODAL: 'UI_HIDE_MODAL'
}
